services:
  rabbitmq1:
    image: rabbitmq:3.12.0-rc.3-management-alpine
    hostname: rabbitmq1
    ports:
      - 15672:15672
      - 5672:5672
      - 1883:1883
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - /C/Users/Jan_E/source/repos/RabbitLatencyBenchmark/RabbitLatencyBenchmark/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - /C/Users/Jan_E/source/repos/RabbitLatencyBenchmark/RabbitLatencyBenchmark/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - /C/Users/Jan_E/source/repos/RabbitLatencyBenchmark/RabbitLatencyBenchmark/clusterentrypoint.sh:/usr/local/bin/clusterentrypoint.sh
    entrypoint: /usr/local/bin/clusterentrypoint.sh
  rabbitmq2:
    image: rabbitmq:3.12.0-rc.3-management-alpine
    hostname: rabbitmq2
    ports:
      - 15673:15672
      - 5673:5672
      - 1884:1883
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - JOIN_CLUSTER_HOST=rabbitmq1
    volumes:
      - /C/Users/Jan_E/source/repos/RabbitLatencyBenchmark/RabbitLatencyBenchmark/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - /C/Users/Jan_E/source/repos/RabbitLatencyBenchmark/RabbitLatencyBenchmark/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - /C/Users/Jan_E/source/repos/RabbitLatencyBenchmark/RabbitLatencyBenchmark/clusterentrypoint.sh:/usr/local/bin/clusterentrypoint.sh
    entrypoint: /usr/local/bin/clusterentrypoint.sh
  rabbitmq3:
    image: rabbitmq:3.12.0-rc.3-management-alpine
    hostname: rabbitmq3
    ports:
      - 15674:15672
      - 5674:5672
      - 1885:1883
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - JOIN_CLUSTER_HOST=rabbitmq1
    volumes:
      - /C/Users/Jan_E/source/repos/RabbitLatencyBenchmark/RabbitLatencyBenchmark/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - /C/Users/Jan_E/source/repos/RabbitLatencyBenchmark/RabbitLatencyBenchmark/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - /C/Users/Jan_E/source/repos/RabbitLatencyBenchmark/RabbitLatencyBenchmark/clusterentrypoint.sh:/usr/local/bin/clusterentrypoint.sh
    entrypoint: /usr/local/bin/clusterentrypoint.sh