services:
  rabbit:
    image: rabbitmq:3.12.0-rc.3-management-alpine
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - /C/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf